
services:
  app:
    build:
      context: ../project
      dockerfile: Dockerfile
    container_name: laravel_shop_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../project:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_shop_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_shop
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel_network

  nginx:
    image: nginx:1.25-alpine
    container_name: laravel_shop_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../project:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge